packages:
  - ./.
  - location: ../test-types
    extra-dep: true
  - location: _build/ghcjs-ffiqq
    extra-dep: true
  - location: _build/ghcjs-jsval-combinators
    extra-dep: true
  - location: _build/ghcjs-servant-client
    extra-dep: true

resolver: lts-5.12

compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
